import ProductListClient from "@/components/i-tech-cards/product-list-client";
import { fetchAllProducts } from "@/lib/data/products";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function Home() {
  return <></>;
}
